# Generated by Django 4.0.5 on 2022-06-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.CharField(max_length=255, verbose_name='Video Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('published_on', models.DateTimeField(verbose_name='publishing datetime')),
                ('thumbnail_url', models.URLField(max_length=255, verbose_name='Thumbnail URL')),
                ('video_link', models.URLField(max_length=255, verbose_name='Video Link')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['-published_on'],
            },
        ),
    ]
